name = "CTM: Cogs and Canvas"
author = "CTM Staff"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a3d0f7dcdb33bbd947b741a56b5b7988bd761945971b091039c92eac7faa937"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
