name = "CTM: Cogs and Canvas"
author = "CTM Staff"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9865c6ff927b9ea858ab4e6df9319c484b15ffdacd2ec8128fec43c46becdf5a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
