name = "CTM: Cogs and Canvas"
author = "CTM Staff"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cae278d03f426c97fdbfd26f67d4efd18581e8d0f19ea1a1ba4ca8ece2e8dd72"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
